version: '3'

services: 
  app:
    image: quay.io/keycloak/keycloak:11.0.2
    container_name: microservice-auth-app
    environment: 
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_ADDR=db
      - DB_VENDOR=mysql
      - DB_DATABASE=micro_auth
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
    ports: 
      - 8080:8080
    depends_on: 
      - db
    networks: 
      - default

  db:
    build: ./.docker/mysql
    container_name: micro-auth-db
    restart: always
    tty: true
    environment: 
      - MYSQL_DATABASE=micro_auth
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    networks: 
      - default

networks: 
  default:
    driver: bridge
